# Generated by Django 5.2.6 on 2025-09-24 01:30

import django.db.models.deletion
from django.db import migrations, models, connection


def add_school_field_if_not_exists(apps, schema_editor):
    """Add school field only if it doesn't already exist"""
    table_name = 'accounts_user'
    column_name = 'school_id'

    with connection.cursor() as cursor:
        if connection.vendor == "sqlite":
            # Original SQLite-specific logic
            cursor.execute("PRAGMA table_info(accounts_user)")
            columns = [column[1] for column in cursor.fetchall()]
            exists = column_name in columns
        elif connection.vendor == "mysql":
            # MySQL-compatible check using INFORMATION_SCHEMA
            cursor.execute(
                """
                SELECT COLUMN_NAME
                FROM INFORMATION_SCHEMA.COLUMNS
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = %s
                  AND COLUMN_NAME = %s
                """,
                [table_name, column_name],
            )
            exists = cursor.fetchone() is not None
        else:
            # For other backends, assume it exists to avoid breaking migrations
            exists = True

        if exists:
            return

        # Add the school field if it doesn't exist
        if connection.vendor == "sqlite":
            cursor.execute(
                'ALTER TABLE accounts_user ADD COLUMN school_id BIGINT NULL '
                'REFERENCES accounts_school(id) DEFERRABLE INITIALLY DEFERRED'
            )
        elif connection.vendor == "mysql":
            # Basic BIGINT NULL column; FK constraints can be managed separately
            cursor.execute(
                'ALTER TABLE accounts_user '
                'ADD COLUMN school_id BIGINT NULL'
            )


def remove_profile_picture_if_exists(apps, schema_editor):
    """Drop profile_picture column only if it exists (for MySQL compatibility)."""
    table_name = 'accounts_user'
    column_name = 'profile_picture'

    with connection.cursor() as cursor:
        if connection.vendor == 'mysql':
            # Check INFORMATION_SCHEMA for the column
            cursor.execute(
                """
                SELECT COLUMN_NAME
                FROM INFORMATION_SCHEMA.COLUMNS
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = %s
                  AND COLUMN_NAME = %s
                """,
                [table_name, column_name],
            )
            exists = cursor.fetchone() is not None
        elif connection.vendor == 'sqlite':
            cursor.execute(f"PRAGMA table_info({table_name})")
            columns = [column[1] for column in cursor.fetchall()]
            exists = column_name in columns
        else:
            # Fallback: attempt to drop and ignore failure
            exists = True

        if not exists:
            return

        try:
            cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN {column_name}")
        except Exception:
            # If the column can't be dropped for some reason, don't fail the migration
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_school_user_profile_picture'),
    ]

    operations = [
        migrations.RunPython(
            remove_profile_picture_if_exists,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            add_school_field_if_not_exists,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
