# Generated by Django 5.2.6 on 2025-09-24 01:30

import django.db.models.deletion
from django.db import migrations, models, connection


def add_school_field_if_not_exists(apps, schema_editor):
    """Add school field only if it doesn't already exist"""
    # This Raw SQL is SQLite-specific. Skip when running on other backends
    # such as MySQL.
    if connection.vendor != "sqlite":
        return

    with connection.cursor() as cursor:
        # Check if school_id column exists
        cursor.execute("PRAGMA table_info(accounts_user)")
        columns = [column[1] for column in cursor.fetchall()]

        if 'school_id' not in columns:
            # Add the school field if it doesn't exist
            cursor.execute('ALTER TABLE accounts_user ADD COLUMN school_id BIGINT NULL REFERENCES accounts_school(id) DEFERRABLE INITIALLY DEFERRED')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_school_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RunPython(
            add_school_field_if_not_exists,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
