# Generated by Django 5.2.6 on 2025-10-13 23:38

from django.db import migrations, models
from django.db import connection


def add_profile_picture_if_not_exists(apps, schema_editor):
    table_name = 'accounts_user'
    column_name = 'profile_picture'

    with connection.cursor() as cursor:
        if connection.vendor == "sqlite":
            cursor.execute(f"PRAGMA table_info({table_name})")
            columns = [column[1] for column in cursor.fetchall()]
            exists = column_name in columns
        elif connection.vendor == "mysql":
            cursor.execute(
                """
                SELECT COLUMN_NAME
                FROM INFORMATION_SCHEMA.COLUMNS
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = %s
                  AND COLUMN_NAME = %s
                """,
                [table_name, column_name],
            )
            exists = cursor.fetchone() is not None
        else:
            # Unknown backend: avoid breaking migrations by assuming the column exists.
            exists = True

    if exists:
        return

    User = apps.get_model('accounts', 'User')
    field = models.ImageField(blank=True, null=True, upload_to='avatars/')
    field.set_attributes_from_name(column_name)
    schema_editor.add_field(User, field)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_school_feature_flags_school_is_trial_and_more'),
    ]

    operations = [
        migrations.RunPython(
            add_profile_picture_if_not_exists,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
