# Generated by Django 5.2.6 on 2025-10-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='homepage',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
