# Generated by Django 5.2.9 on 2026-02-01 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_maintenancenotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_first_name', models.CharField(blank=True, default='', max_length=150)),
                ('admin_last_name', models.CharField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('password_hash', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RenameIndex(
            model_name='schooldomain',
            new_name='accounts_sc_domain_5830d5_idx',
            old_name='accounts_sc_domain_8cfd4e_idx',
        ),
        migrations.RenameIndex(
            model_name='schooldomain',
            new_name='accounts_sc_school__f0a408_idx',
            old_name='accounts_sc_school__7b8f1a_idx',
        ),
        migrations.RenameIndex(
            model_name='systemhealthevent',
            new_name='accounts_sy_created_941f6b_idx',
            old_name='accounts_sys_created_3c9a2b_idx',
        ),
        migrations.RenameIndex(
            model_name='systemhealthevent',
            new_name='accounts_sy_compone_af2db8_idx',
            old_name='accounts_sys_compone_f4a9a0_idx',
        ),
        migrations.RenameIndex(
            model_name='systemhealthevent',
            new_name='accounts_sy_compone_c43465_idx',
            old_name='accounts_sys_compone_87772c_idx',
        ),
        migrations.AddField(
            model_name='demorequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_demo_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='created_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_requests', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_demo_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='demorequest',
            index=models.Index(fields=['status', 'created_at'], name='accounts_de_status_e7df9b_idx'),
        ),
        migrations.AddIndex(
            model_name='demorequest',
            index=models.Index(fields=['admin_email'], name='accounts_de_admin_e_96fd90_idx'),
        ),
    ]
