# Generated by Django 5.2.9 on 2026-02-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_demorequest'),
        ('accounts', '0020_demorequest_and_more'),
    ]

    operations = [
    ]
