# Generated by Django 5.2.9 on 2026-02-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_user_profile_picture'),
    ]

    operations = [
    ]
