# Generated by Django 5.2.9 on 2026-02-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_dashboardshowcaseitem'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dashboardshowcaseitem',
            new_name='accounts_da_sort_or_f23223_idx',
            old_name='accounts_da_sort_or_e39192_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardshowcaseitem',
            new_name='accounts_da_created_c39bac_idx',
            old_name='accounts_da_created_98f73c_idx',
        ),
    ]
