# Generated by Django 5.2.9 on 2026-02-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_rename_accounts_da_sort_or_e39192_idx_accounts_da_sort_or_f23223_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolintegrationsettings',
            name='textwave_base_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolintegrationsettings',
            name='textwave_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='schoolintegrationsettings',
            name='textwave_sender_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolintegrationsettings',
            name='sms_provider',
            field=models.CharField(blank=True, choices=[('textwave', 'TextWave'), ('africastalking', "Africa's Talking")], default='textwave', max_length=50),
        ),
    ]
