# Generated by Django 5.2.12 on 2026-03-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_textwave_integration_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='enable_fee_reset',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
