# Generated by Django 6.0.2 on 2026-03-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_school_enable_fee_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='teacher_onboarding_video_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
