# Generated by Django 6.0.2 on 2026-03-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_systemconfig_teacher_onboarding_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='teacher_onboarding_video_url_mobile',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
