# Generated by Django 6.0.2 on 2026-03-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_systemconfig_teacher_onboarding_video_url_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='video_url_attendance',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='video_url_attendance_mobile',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='video_url_grades',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='video_url_grades_mobile',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='video_url_messages',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='video_url_messages_mobile',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='video_url_results',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='video_url_results_mobile',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
