# Generated by Django 4.2.7 on 2026-05-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_usersession'),
        ('accounts', '0033_user_deleted_at_user_deleted_by_user_is_deleted'),
    ]

    operations = [
    ]
