# Generated by Django 4.2.7 on 2026-05-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_merge_20260519_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demorequest',
            name='admin_first_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='admin_last_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='school_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='nonteachingstaff',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='nonteachingstaff',
            name='department',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='nonteachingstaff',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='nonteachingstaff',
            name='national_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='nonteachingstaff',
            name='nhif_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='nonteachingstaff',
            name='nssf_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='nonteachingstaff',
            name='position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='motto',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='trial_student_limit',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='schooldomain',
            name='domain',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolintegrationsettings',
            name='at_api_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolintegrationsettings',
            name='at_sender_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='schoolintegrationsettings',
            name='at_username',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolintegrationsettings',
            name='sms_provider',
            field=models.CharField(blank=True, choices=[('textwave', 'TextWave'), ('africastalking', "Africa's Talking")], default='textwave', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolintegrationsettings',
            name='smtp_from_email',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='schoolintegrationsettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='schoolintegrationsettings',
            name='smtp_password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolintegrationsettings',
            name='smtp_port',
            field=models.PositiveSmallIntegerField(default=587),
        ),
        migrations.AlterField(
            model_name='schoolintegrationsettings',
            name='smtp_username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolintegrationsettings',
            name='textwave_api_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolintegrationsettings',
            name='textwave_base_url',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='schoolintegrationsettings',
            name='textwave_sender_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='default_domain',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='teacher_onboarding_video_url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='teacher_onboarding_video_url_mobile',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='video_url_attendance',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='video_url_attendance_mobile',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='video_url_grades',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='video_url_grades_mobile',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='video_url_messages',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='video_url_messages_mobile',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='video_url_print_results',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='video_url_print_results_mobile',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='video_url_results',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='video_url_results_mobile',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='systemhealthevent',
            name='component',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('login', 'Login'), ('queries', 'Fetching Queries'), ('payment_mpesa', 'Payments (M-Pesa)'), ('payment_bank', 'Payments (Bank)')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='systemhealthevent',
            name='context',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('finance', 'Finance'), ('non_teaching', 'Non-Teaching Staff')], max_length=15),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='device_name',
            field=models.CharField(blank=True, default='Unknown Device', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='jti',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
