# Generated by Django 5.2.6 on 2025-10-26 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_school_homepage'),
        ('communications', '0008_event_completed_event_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('recipient', models.CharField(max_length=255)),
                ('ok', models.BooleanField(default=False)),
                ('message_snippet', models.CharField(blank=True, default='', max_length=300)),
                ('context', models.CharField(blank=True, default='', help_text='e.g., message:123, campaign:45', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to='accounts.school')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'indexes': [models.Index(fields=['created_at'], name='communicati_created_42cc0f_idx'), models.Index(fields=['channel', 'created_at'], name='communicati_channel_548730_idx')],
            },
        ),
    ]
