# Generated by Django 5.2.6 on 2025-10-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_deliverylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrearsmessagecampaign',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='arrearsmessagecampaign',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=20),
        ),
    ]
