# Generated by Django 5.2.6 on 2025-10-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0010_arrearsmessagecampaign_cancel_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_broadcast',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
