# Generated by Django 5.2.9 on 2026-02-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0012_servicereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='send_email',
            field=models.BooleanField(default=True),
        ),
    ]
