# Generated by Django 5.2.9 on 2026-02-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0013_message_delivery_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylog',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
