# Generated by Django 5.2.9 on 2026-02-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_textwave_integration_settings'),
        ('communications', '0015_deliveryjob'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deliveryjob',
            new_name='communicati_status_d3cac2_idx',
            old_name='communicati_status_0c0f1f_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryjob',
            new_name='communicati_message_9b8714_idx',
            old_name='communicati_message_6c2d8e_idx',
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('queued', 'Queued'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='context',
            field=models.CharField(blank=True, default='', help_text='e.g., message:123, campaign:45, type:verification', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='message_snippet',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['status'], name='communicati_status_0d7ac1_idx'),
        ),
    ]
