# Generated by Django 5.2.9 on 2026-05-19 17:08

from django.db import migrations, models

from edutrack.mysql_migration import drop_checks_for_app_models

_COMMUNICATIONS_MODELS = (
    'arrearsmessagecampaign', 'deliveryjob', 'deliverylog', 'event', 'message',
    'notification', 'servicereview',
)


def drop_mysql_checks_forward(apps, schema_editor):
    drop_checks_for_app_models(apps, schema_editor, 'communications', _COMMUNICATIONS_MODELS)


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0017_add_deliverylog_indexes'),
    ]

    operations = [
        migrations.RunPython(drop_mysql_checks_forward, migrations.RunPython.noop),
        migrations.RenameIndex(
            model_name='deliverylog',
            new_name='communicati_school__d4dbf1_idx',
            old_name='comm_del_school_created_idx',
        ),
        migrations.RenameIndex(
            model_name='deliverylog',
            new_name='communicati_school__c0961e_idx',
            old_name='comm_del_school_channel_created_idx',
        ),
        migrations.RenameIndex(
            model_name='deliverylog',
            new_name='communicati_school__129895_idx',
            old_name='comm_del_school_status_idx',
        ),
        migrations.AlterField(
            model_name='arrearsmessagecampaign',
            name='email_failed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arrearsmessagecampaign',
            name='email_sent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arrearsmessagecampaign',
            name='email_subject',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='arrearsmessagecampaign',
            name='min_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='arrearsmessagecampaign',
            name='sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arrearsmessagecampaign',
            name='sms_failed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arrearsmessagecampaign',
            name='sms_sent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arrearsmessagecampaign',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=15),
        ),
        migrations.AlterField(
            model_name='deliveryjob',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deliveryjob',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='deliveryjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='context',
            field=models.CharField(blank=True, default='', help_text='e.g., message:123, campaign:45, type:verification', max_length=50),
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='recipient',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('queued', 'Queued'), ('pending', 'Pending')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='audience',
            field=models.CharField(choices=[('all', 'All'), ('students', 'Students'), ('teachers', 'Teachers'), ('parents', 'Parents'), ('staff', 'Staff')], default='all', max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal')], default='internal', max_length=15),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('finance', 'Finance')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='system_tag',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('in_app', 'In-App'), ('sms', 'SMS'), ('email', 'Email')], default='in_app', max_length=15),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='page_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
