# Generated by Django 5.2.6 on 2025-10-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0026_student_birth_certificate_no_student_guardian_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, help_text='When false, the student is inactive: excluded from exams, fees, messaging, and login disabled.'),
        ),
    ]
