# Generated by Django 5.2.9 on 2026-01-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0029_teacherduty'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='out_of',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
