# Generated by Django 5.2.9 on 2026-01-26 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0030_examresult_out_of'),
        ('accounts', '0013_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='stage',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('junior', 'Junior Secondary')], default='', help_text='Primary: Grades 1-6; Junior Secondary: Grades 7-9', max_length=20),
        ),
        migrations.CreateModel(
            name='StageGradingBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('primary', 'Primary'), ('junior', 'Junior Secondary')], max_length=20)),
                ('grade', models.CharField(max_length=5)),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.school')),
            ],
            options={
                'ordering': ['stage', 'order', '-max'],
                'unique_together': {('school', 'stage', 'grade')},
            },
        ),
    ]
