# Generated by Django 5.2.6 on 2026-01-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0031_class_stage_stagegradingband'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
