# Generated by Django 5.2.9 on 2026-02-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0033_recycle_bin_academics'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_transferred',
            field=models.BooleanField(default=False, help_text='When true, the student has been transferred out: excluded from all school operations.'),
        ),
    ]
