# Generated by Django 5.2.9 on 2026-03-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0035_class_deleted_at_class_deleted_by_class_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='last_idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
