# Generated by Django 5.2.9 on 2026-05-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0036_examresult_last_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
