# Generated by Django 6.0.2 on 2026-05-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0037_examresult_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='label',
            field=models.CharField(help_text='Display label e.g. 2024/2025', max_length=10),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='level',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=15),
        ),
        migrations.AlterField(
            model_name='class',
            name='grade_level',
            field=models.CharField(help_text="Grade level (e.g., '1', 'Grade 1')", max_length=15),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='class',
            name='stage',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('junior', 'Junior Secondary')], default='', help_text='Primary: Grades 1-6; Junior Secondary: Grades 7-9', max_length=15),
        ),
        migrations.AlterField(
            model_name='competency',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='competency',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='exam',
            name='grade_level_tag',
            field=models.CharField(blank=True, db_index=True, help_text="Grade level at the time the exam was set (e.g., 'Grade 4')", max_length=15),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='term',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')]),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='last_idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='topic',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='week',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Week number within the term (1-13)', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='stagegradingband',
            name='grade',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='stagegradingband',
            name='max',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='stagegradingband',
            name='min',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='stagegradingband',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stagegradingband',
            name='stage',
            field=models.CharField(choices=[('primary', 'Primary'), ('junior', 'Junior Secondary')], max_length=15),
        ),
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_no',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_certificate_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_passport_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='upi_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='studentclasshistory',
            name='action',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('promoted', 'Promoted'), ('moved', 'Moved'), ('graduated', 'Graduated'), ('unassigned', 'Unassigned')], default='moved', max_length=15),
        ),
        migrations.AlterField(
            model_name='studentclasshistory',
            name='note',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='studentclasshistory',
            name='term',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentclasshistory',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('language', 'Language'), ('science', 'Science'), ('arts', 'Arts'), ('humanities', 'Humanities'), ('other', 'Other')], default='other', max_length=15),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectcomponent',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectcomponent',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectcomponent',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subjectgradingband',
            name='grade',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='subjectgradingband',
            name='max',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='subjectgradingband',
            name='min',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='subjectgradingband',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacherduty',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('canceled', 'Canceled')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='teacherduty',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='tsc_number',
            field=models.CharField(blank=True, help_text='T.S.C number', max_length=30, null=True, unique=True),
        ),
    ]
