# Generated by Django 5.2.6 on 2025-10-20 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_profile_picture'),
        ('finance', '0007_alter_classfee_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='accounts.school')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'unique_together': {('school', 'key')},
            },
        ),
    ]
