# Generated by Django 5.2.6 on 2025-11-02 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0028_studentclasshistory'),
        ('finance', '0008_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('coop', 'Co-op'), ('mpesa', 'M-Pesa'), ('bank', 'Bank'), ('manual', 'Manual')], default='bank', max_length=20)),
                ('external_id', models.CharField(blank=True, help_text='Provider reference/unique id', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('reference', models.CharField(blank=True, help_text='Receipt/transaction code', max_length=100)),
                ('narration', models.TextField(blank=True)),
                ('account_ref', models.CharField(blank=True, help_text='Account reference passed to gateway (e.g., INV123, admission no)', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('payer_name', models.CharField(blank=True, max_length=255)),
                ('value_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched (Student identified)'), ('reconciled', 'Reconciled (Applied to invoices)'), ('ignored', 'Ignored')], db_index=True, default='pending', max_length=20)),
                ('match_confidence', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_matches', to='finance.invoice')),
                ('matched_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_payments', to='academics.student')),
            ],
            options={
                'verbose_name': 'Incoming Payment',
                'verbose_name_plural': 'Incoming Payments',
                'indexes': [models.Index(fields=['status'], name='finance_inc_status_77b1e1_idx'), models.Index(fields=['source', 'external_id'], name='finance_inc_source_9c0e0a_idx')],
            },
        ),
    ]
