# Generated by Django 5.2.6 on 2025-11-07 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_role_nonteachingstaff'),
        ('finance', '0010_feecategory_is_special_studentfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowances', models.JSONField(blank=True, default=list)),
                ('deductions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_payrolls', to='accounts.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='accounts.nonteachingstaff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffPayslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('basic', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowances', models.JSONField(blank=True, default=list)),
                ('deductions', models.JSONField(blank=True, default=list)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_payslips', to='accounts.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='accounts.nonteachingstaff')),
            ],
            options={
                'unique_together': {('staff', 'year', 'month')},
            },
        ),
    ]
