# Generated by Django 5.2.6 on 2025-11-07 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_staffpayroll_staffpayslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payee',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory'),
        ),
    ]
