# Generated by Django 5.2.9 on 2026-01-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_passwordresetcode'),
        ('finance', '0012_expense_payee_alter_expense_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffpayslip',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='staffpayroll',
            name='payout_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='staffpayslip',
            index=models.Index(fields=['school', 'staff', 'year', 'month'], name='finance_sta_school__6c014a_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffpayslip',
            constraint=models.UniqueConstraint(fields=('school', 'staff', 'year', 'month'), name='uniq_staff_month_school'),
        ),
    ]
