# Generated by Django 5.2.12 on 2026-03-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_staffpayslip_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('coop', 'Co-op Lipa na M-Pesa'), ('bank', 'Bank'), ('cash', 'Cash'), ('cheque', 'Cheque')], default='mpesa', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='key',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('coop', 'Co-op Lipa na M-Pesa'), ('bank', 'Bank'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=20),
        ),
    ]
