# Generated by Django 6.0.2 on 2026-05-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_payment_method_alter_paymentmethod_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfee',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='classfee',
            name='term',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')]),
        ),
        migrations.AlterField(
            model_name='classfee',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payee',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feecategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='incomingpayment',
            name='account_ref',
            field=models.CharField(blank=True, help_text='Account reference passed to gateway (e.g., INV123, admission no)', max_length=50),
        ),
        migrations.AlterField(
            model_name='incomingpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='incomingpayment',
            name='currency',
            field=models.CharField(default='KES', max_length=5),
        ),
        migrations.AlterField(
            model_name='incomingpayment',
            name='external_id',
            field=models.CharField(blank=True, help_text='Provider reference/unique id', max_length=50),
        ),
        migrations.AlterField(
            model_name='incomingpayment',
            name='payer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='incomingpayment',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='incomingpayment',
            name='reference',
            field=models.CharField(blank=True, help_text='Receipt/transaction code', max_length=50),
        ),
        migrations.AlterField(
            model_name='incomingpayment',
            name='source',
            field=models.CharField(choices=[('coop', 'Co-op'), ('mpesa', 'M-Pesa'), ('bank', 'Bank'), ('manual', 'Manual')], default='bank', max_length=15),
        ),
        migrations.AlterField(
            model_name='incomingpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched (Student identified)'), ('reconciled', 'Reconciled (Applied to invoices)'), ('ignored', 'Ignored')], db_index=True, default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partial')], default='unpaid', max_length=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='term',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')], null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mpesaconfig',
            name='consumer_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mpesaconfig',
            name='consumer_secret',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mpesaconfig',
            name='environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=10),
        ),
        migrations.AlterField(
            model_name='mpesaconfig',
            name='passkey',
            field=models.CharField(help_text='Lipa Na Mpesa Online passkey', max_length=100),
        ),
        migrations.AlterField(
            model_name='mpesaconfig',
            name='short_code',
            field=models.CharField(help_text='Till or PayBill number', max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('coop', 'Co-op Lipa na M-Pesa'), ('bank', 'Bank'), ('cash', 'Cash'), ('cheque', 'Cheque')], default='mpesa', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pocketmoneytransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='pocketmoneywallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='staffpayroll',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staffpayroll',
            name='payout_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffpayslip',
            name='basic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staffpayslip',
            name='gross_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staffpayslip',
            name='month',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='staffpayslip',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staffpayslip',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='term',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')]),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
