from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from .views import (
    me,
    users,
    create_user,
    update_user_status,
    reset_password,
    school_me,
    update_user,
    change_password,
    school_info,
    trial_signup,
    request_demo,
    verify_email,
    logout,
    logout_all,
    site_context,
    school_public,
    school_teachers_public,
    teacher_public_detail,
    non_teaching_staff,
    non_teaching_staff_detail,
    password_reset_request,
    password_reset_verify,
    password_reset_confirm,
    users_delete_otp_request,
    users_delete_otp_confirm,
    maintenance_notice,
    superadmin_schools,
    superadmin_demo_requests,
    superadmin_demo_request_approve,
    superadmin_demo_request_reject,
    superadmin_system_analysis,
    superadmin_maintenance_notice,
    superadmin_school_detail,
    superadmin_school_add_domain,
    superadmin_domain_detail,
    superadmin_school_integrations,
    superadmin_school_payment_methods,
    superadmin_school_mpesa_config,
    TokenObtainPairViewWithLogging,
)

urlpatterns = [
    path('token/', TokenObtainPairViewWithLogging.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('logout/', logout, name='logout'),
    path('logout-all/', logout_all, name='logout_all'),
    path('me/', me, name='me'),
    path('users/', users, name='users'),
    path('users/create/', create_user, name='users-create'),
    path('users/update/', update_user, name='users-update'),
    path('users/status/', update_user_status, name='users-status'),
    path('users/reset_password/', reset_password, name='users-reset-password'),
    path('users/change_password/', change_password, name='users-change-password'),
    path('users/delete/otp/request/', users_delete_otp_request, name='users-delete-otp-request'),
    path('users/delete/otp/confirm/', users_delete_otp_confirm, name='users-delete-otp-confirm'),
    path('password-reset/request/', password_reset_request, name='password-reset-request'),
    path('password-reset/verify/', password_reset_verify, name='password-reset-verify'),
    path('password-reset/confirm/', password_reset_confirm, name='password-reset-confirm'),
    path('school/me/', school_me, name='school-me'),
    path('school/info/', school_info, name='school-info'),
    path('site-context/', site_context, name='site-context'),
    path('maintenance/', maintenance_notice, name='maintenance-notice'),
    path('school/public/', school_public, name='school-public'),
    path('school/teachers/', school_teachers_public, name='school-teachers-public'),
    path('school/teachers/<int:id>/', teacher_public_detail, name='teacher-public-detail'),
    path('request-demo/', request_demo, name='request-demo'),
    path('trial-signup/', trial_signup, name='trial-signup'),
    path('verify-email/', verify_email, name='verify-email'),
    path('non-teaching-staff/', non_teaching_staff, name='non-teaching-staff'),
    path('non-teaching-staff/<int:id>/', non_teaching_staff_detail, name='non-teaching-staff-detail'),
    path('superadmin/schools/', superadmin_schools, name='superadmin-schools'),
    path('superadmin/demo-requests/', superadmin_demo_requests, name='superadmin-demo-requests'),
    path('superadmin/demo-requests/<int:id>/approve/', superadmin_demo_request_approve, name='superadmin-demo-requests-approve'),
    path('superadmin/demo-requests/<int:id>/reject/', superadmin_demo_request_reject, name='superadmin-demo-requests-reject'),
    path('superadmin/system-analysis/', superadmin_system_analysis, name='superadmin-system-analysis'),
    path('superadmin/maintenance/', superadmin_maintenance_notice, name='superadmin-maintenance-notice'),
    path('superadmin/schools/<int:id>/', superadmin_school_detail, name='superadmin-school-detail'),
    path('superadmin/schools/<int:id>/domains/', superadmin_school_add_domain, name='superadmin-school-add-domain'),
    path('superadmin/schools/<int:id>/integrations/', superadmin_school_integrations, name='superadmin-school-integrations'),
    path('superadmin/schools/<int:id>/payment-methods/', superadmin_school_payment_methods, name='superadmin-school-payment-methods'),
    path('superadmin/schools/<int:id>/mpesa-config/', superadmin_school_mpesa_config, name='superadmin-school-mpesa-config'),
    path('superadmin/domains/<int:id>/', superadmin_domain_detail, name='superadmin-domain-detail'),
]
